##
## !WARNING!
##         
## This file is managed by chezmoi. To edit use chezmoi edit ~/.config/tmux/tmux.conf
##
## !WARNING!
##

# --- Basic config ---
set -g mouse on             # enable mouse mode (scrolling/clicking)
set -g history-limit 100000 # Lots of scrollback

set -g base-index 1         # count windows from 1
setw -g pane-base-index 1   # count panes from 1
set -g window-status-format '  #I:#W  '            # status format becomes, e.g. 1:zsh
set -g window-status-current-format ' [#I:#W] '  # selected window surrounded by brackets, e.g. [1:zsh]
set -g status on   # make status 1 line (this is defult but just being explicit)

set -g default-terminal "tmux-256color" # color support
set -ga terminal-overrides ",*:RGB"     # color supprt

set -sg escape-time 10      # Faster escape handling (helps with Vim)

# --- Plugin paths ---
set -g @plugin_dir "$HOME/.config/tmux/plugins"

# --- tmux-prefix-highlight config ---
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'
set -g status-right "#{prefix_highlight} %H:%M %d-%b" # add prefix-highlight to right side of status bar

# --- Auto Plugin bootstrap Code ---
if-shell "test -f $HOME/.config/tmux/plugins/tmux-prefix-highlight/prefix_highlight.tmux" \
  "run-shell $HOME/.config/tmux/plugins/tmux-prefix-highlight/prefix_highlight.tmux"
