##
## !WARNING!
##         
## This file is managed by chezmoi. To edit use chezmoi edit ~/.config/tmux/tmux.conf
##
## !WARNING!
##

# --- Basic config ---
set -g mouse on             # enable mouse mode (scrolling/clicking)
set -g set-clipboard on
set -g history-limit 100000 # Lots of scrollback
set -g extended-keys always                    # dont strip keyboard modified
set -as terminal-features 'xterm*:extkeys'     # tells tmux that my outer terminal (e.g. iTerm2) is xterm compatible
set -g extended-keys-format csi-u
set -sg escape-time 10      # Faster escape handling (helps with Vim)

set -g base-index 1         # count windows from 1
setw -g pane-base-index 1   # count panes from 1

#
# --- status bar ---
#
set -g status on
set -g status-interval 5
set -g status-justify absolute-centre

# Base colors
set -g status-style 'bg=colour236,fg=colour248'

# Left status: Session name pill followed by prefix highlight
set -g status-left-length 50
set -g status-left "#[fg=colour236,bg=colour109,bold] #S #[fg=colour109,bg=colour236,nobold,nounderscore,noitalics] #{prefix_highlight}"

# Window list format (Pill style with chevrons)
set -g window-status-separator "#[bg=colour236] "
set -g window-status-format "#[fg=colour236,bg=colour239,nobold,nounderscore,noitalics]#[fg=colour248,bg=colour239] #I  #W #[fg=colour239,bg=colour236,nobold,nounderscore,noitalics]"
set -g window-status-current-format "#[fg=colour236,bg=colour214,nobold,nounderscore,noitalics]#[fg=colour236,bg=colour214,bold] #I  #W #[fg=colour214,bg=colour236,nobold,nounderscore,noitalics]"

#
# colors
#
set -g default-terminal "tmux-256color" # color support
set -ga terminal-overrides ",*:RGB"     # color supprt

#
# --- panes / windows ---
#
set -g pane-border-format "#{?pane_active,#[fg=colour46] ◉ ACTIVE #[default],#[fg=colour240] ○ inactive #[default]}"
set -g pane-border-status top
set -g window-style 'fg=colour237,bg=colour234'
set -g pane-border-style 'fg=colour236,bg=default'

#
# --- active panes / windows --
#
set -g window-active-style 'fg=colour188,bg=colour232'
set -g pane-active-border-style 'fg=colour236,bg=default'

# --- Plugin paths ---
set -g @plugin_dir "$HOME/.config/tmux/plugins"

# --- tmux-prefix-highlight config ---
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'
set -g @prefix_highlight_empty_prompt ''

# Right status: Chevron + UTC time
set -g status-right-length 50
set -g status-right "#[fg=colour109,bg=colour236,nobold,nounderscore,noitalics]#[fg=colour236,bg=colour109,bold] #(date -u +'%%Y-%%m-%%dT%%H:%%M UTC') "

# --- Auto Plugin bootstrap Code ---
if-shell "test -f $HOME/.config/tmux/plugins/tmux-prefix-highlight/prefix_highlight.tmux" \
  "run-shell $HOME/.config/tmux/plugins/tmux-prefix-highlight/prefix_highlight.tmux"

if-shell "test -f $HOME/.config/tmux/plugins/tmux-resurrect/resurrect.tmux" \
  "run-shell $HOME/.config/tmux/plugins/tmux-resurrect/resurrect.tmux"
